services:
#  frontend:
#    build: ./frontend
#    ports:
#      - "5173:5173"
#    volumes:
#      - ./frontend:/app
#    restart: unless-stopped


#  db:
#    image: postgres:16
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB}
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/ # Persist data even if container stops
#    ports:
#      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hypertube_backend
    volumes:
      - ./backend:/app      # Mount local files for real-time development
    ports:
      - "8000:8000"
