services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: hypertube_backend
    volumes:
      - ./app:/app      # Mount local files for real-time development
    ports:
      - "8000:8000"
